### ISSUE TITLE
Extra quotes on token

### ISSUE THREAD

**Issue by poonasor** [michael5r/mmm-nest-cameras#2]
Not sure if there is suppose to be an " quotes on the token generated

**Comment by poonasor** [comment]
just confirmed - not an extra quote but a missing quote at the end of the token

**Comment by michael5r** [comment]
You're right - I'll get the `getToken.sh` script updated asap. Thanks for the report!

**Comment by michael5r** [comment]
Fixed in version `1.1.0`
